export default {
    GET_POKEMON: "POKEMON/GET_POKEMON",    
    GET_POKEMON_REQUEST: "POKEMON/GET_POKEMON/request",    
    GET_POKEMON_SUCCESS: "POKEMON/GET_POKEMON/success",    
    GET_POKEMON_FAILURE: "POKEMON/GET_POKEMON/failure",    
}